---
- name: user | Ensure group exists
  ansible.builtin.group:
    name: "{{ foundryvtt_docker_group }}"
    gid: "{{ foundryvtt_docker_gid }}"
    state: present

- name: user | Ensure user exists with gid
  ansible.builtin.user:
    name: "{{ foundryvtt_docker_user }}"
    uid: "{{ foundryvtt_docker_uid }}"
    state: "present"

- name: user | Ensure that docker network exists
  community.docker.docker_network:
    name: "{{ foundryvtt_docker_network_name }}"
