---
- name: Foundryvtt systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Foundryvtt restart
  ansible.builtin.service:
    name: "foundryvtt"
    state: restarted
    enabled: true
